"""empty message

Revision ID: 57205d175a06
Revises: 70ec23792247
Create Date: 2025-05-25 02:39:54.477949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57205d175a06'
down_revision = '70ec23792247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False, server_default=sa.text('1')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_cart', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
