"""empty message

Revision ID: 70ec23792247
Revises: f34212040622
Create Date: 2025-05-22 21:42:01.678762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70ec23792247'
down_revision = 'f34212040622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_cart', schema=None) as batch_op:
        batch_op.drop_column('cart_id')

    # ### end Alembic commands ###
