"""empty message

Revision ID: 995eee0ff552
Revises: ec6d219b184d
Create Date: 2025-05-20 21:13:43.397566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '995eee0ff552'
down_revision = 'ec6d219b184d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=600),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
