"""empty message

Revision ID: bdaca345e234
Revises: 324d35d354fd
Create Date: 2025-05-17 09:37:03.349675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdaca345e234'
down_revision = '324d35d354fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=120), nullable=False))
        batch_op.drop_column('payment_mehotd')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_mehotd', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
